language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - npm install -g ionic
script:
  - npm install
  - npm run build --prod
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1/hio6-6vk48T9wbjGAV6cdjPJGE0xbfbOSA1KhWRQLdE"
