import { Slide } from './slide.model';


export const Slides: Slide[] = [
    // { img: 'assets/images/144.JPG' },
    { img: 'assets/images/12.JPG' },
    { img: 'assets/images/189.PNG' },
    { img: 'assets/images/13.JPG' },
    { img: 'assets/images/14.JPG' },
    { img: 'assets/images/15.JPG' },
    { img: 'assets/images/16.JPG' },
    { img: 'assets/images/17.JPG' },
    { img: 'assets/images/18.JPG' },
    { img: 'assets/images/19.JPG' },
    { img: 'assets/images/110.JPG' },
    { img: 'assets/images/111.JPG' },
    { img: 'assets/images/112.JPG' },
    { img: 'assets/images/11.JPG' },
    { img: 'assets/images/113.JPG' },
    { img: 'assets/images/114.JPG' },
    { img: 'assets/images/115.JPG' },
    { img: 'assets/images/116.JPG' },
    { img: 'assets/images/117.JPG' },
    { img: 'assets/images/118.JPG' },
    { img: 'assets/images/119.JPG' },
    { img: 'assets/images/120.JPG' },
    { img: 'assets/images/121.JPG' },
    { img: 'assets/images/122.JPG' },
    { img: 'assets/images/123.JPG' },
    { img: 'assets/images/124.JPG' },
    { img: 'assets/images/125.JPG' },
    { img: 'assets/images/126.JPG' },
    { img: 'assets/images/127.JPG' },
    { img: 'assets/images/128.JPG' },
    { img: 'assets/images/129.JPG' },
    { img: 'assets/images/130.JPG' },
    { img: 'assets/images/131.JPG' },
    { img: 'assets/images/132.JPG' },
    { img: 'assets/images/133.JPG' },
    { img: 'assets/images/134.JPG' },
    { img: 'assets/images/135.JPG' },
    { img: 'assets/images/136.JPG' },
    { img: 'assets/images/137.JPG' },
    { img: 'assets/images/138.JPG' },
    { img: 'assets/images/139.JPG' },
    { img: 'assets/images/140.JPG' },
    { img: 'assets/images/141.JPG' },
    { img: 'assets/images/142.JPG' },
    { img: 'assets/images/143.JPG' },
    { img: 'assets/images/145.JPG' },
    { img: 'assets/images/146.JPG' },
    { img: 'assets/images/147.JPG' },
    { img: 'assets/images/148.JPG' },
    { img: 'assets/images/149.JPG' },
    { img: 'assets/images/11.PNG' },
    { img: 'assets/images/12.PNG' },
    { img: 'assets/images/13.PNG' },
    { img: 'assets/images/14.PNG' },
    { img: 'assets/images/15.PNG' },
    { img: 'assets/images/16.PNG' },
    { img: 'assets/images/17.PNG' },
    { img: 'assets/images/18.PNG' },
    { img: 'assets/images/19.PNG' },
    { img: 'assets/images/110.PNG' },
    { img: 'assets/images/111.PNG' },
    { img: 'assets/images/112.PNG' },
    { img: 'assets/images/113.PNG' },
    { img: 'assets/images/114.PNG' },
    { img: 'assets/images/115.PNG' },
    { img: 'assets/images/116.PNG' },
    { img: 'assets/images/117.PNG' },
    { img: 'assets/images/118.PNG' },
    { img: 'assets/images/119.PNG' },
    { img: 'assets/images/120.PNG' },
    { img: 'assets/images/121.PNG' },
    { img: 'assets/images/122.PNG' },
    { img: 'assets/images/123.PNG' },
    { img: 'assets/images/124.PNG' },
    { img: 'assets/images/125.PNG' },
    { img: 'assets/images/126.PNG' },
    { img: 'assets/images/127.PNG' },
    { img: 'assets/images/128.PNG' },
    { img: 'assets/images/129.PNG' },
    { img: 'assets/images/130.PNG' },
    { img: 'assets/images/131.PNG' },
    { img: 'assets/images/132.PNG' },
    { img: 'assets/images/133.PNG' },
    { img: 'assets/images/134.PNG' },
    { img: 'assets/images/135.PNG' },
    { img: 'assets/images/136.PNG' },
    { img: 'assets/images/137.PNG' },
    { img: 'assets/images/138.PNG' },
    { img: 'assets/images/139.PNG' },
    { img: 'assets/images/140.PNG' },
    { img: 'assets/images/141.PNG' },
    { img: 'assets/images/142.PNG' },
    { img: 'assets/images/143.PNG' },
    { img: 'assets/images/144.PNG' },
    { img: 'assets/images/145.PNG' },
    { img: 'assets/images/146.PNG' },
    { img: 'assets/images/147.PNG' },
    { img: 'assets/images/148.PNG' },
    { img: 'assets/images/149.PNG' },
    { img: 'assets/images/150.PNG' },
    { img: 'assets/images/151.PNG' },
    { img: 'assets/images/152.PNG' },
    { img: 'assets/images/153.PNG' },
    { img: 'assets/images/154.PNG' },
    { img: 'assets/images/155.PNG' },
    { img: 'assets/images/156.PNG' },
    { img: 'assets/images/157.PNG' },
    { img: 'assets/images/158.PNG' },
    { img: 'assets/images/159.PNG' },
    { img: 'assets/images/160.PNG' },
    { img: 'assets/images/161.PNG' },
    { img: 'assets/images/162.PNG' },
    { img: 'assets/images/163.PNG' },
    { img: 'assets/images/164.PNG' },
    { img: 'assets/images/165.PNG' },
    { img: 'assets/images/166.PNG' },
    { img: 'assets/images/167.PNG' },
    { img: 'assets/images/168.PNG' },
    { img: 'assets/images/169.PNG' },
    { img: 'assets/images/170.PNG' },
    { img: 'assets/images/171.PNG' },
    { img: 'assets/images/172.PNG' },
    { img: 'assets/images/173.PNG' },
    { img: 'assets/images/174.PNG' },
    { img: 'assets/images/175.PNG' },
    { img: 'assets/images/176.PNG' },
    { img: 'assets/images/177.PNG' },
    { img: 'assets/images/178.PNG' },
    { img: 'assets/images/179.PNG' },
    { img: 'assets/images/180.PNG' },
    { img: 'assets/images/181.PNG' },
    { img: 'assets/images/182.PNG' },
    { img: 'assets/images/183.PNG' },
    { img: 'assets/images/184.PNG' },
    { img: 'assets/images/185.PNG' },
    { img: 'assets/images/186.PNG' },
    { img: 'assets/images/187.PNG' },
    { img: 'assets/images/188.PNG' },
    { img: 'assets/images/190.PNG' },
    { img: 'assets/images/191.PNG' },
    { img: 'assets/images/192.PNG' },
    { img: 'assets/images/193.PNG' },
    { img: 'assets/images/194.PNG' },
    { img: 'assets/images/195.PNG' },

    ];

// { img: 'assets/images/16.JPG' },
// { img: 'assets/images/01.JPG' },
// { img: 'assets/images/1.jpg' },
// { img: 'assets/images/2.jpg' },
// { img: 'assets/images/3.jpg' },
// { img: 'assets/images/4.jpg' },
// { img: 'assets/images/02.JPG' },
// { img: 'assets/images/03.JPG' },
// { img: 'assets/images/04.JPG' },
// { img: 'assets/images/05.JPG' },
// { img: 'assets/images/06.JPG' },
// { img: 'assets/images/07.JPG' },
// { img: 'assets/images/08.JPG' },
// { img: 'assets/images/09.JPG' },
// { img: 'assets/images/10.JPG' },
// { img: 'assets/images/11.JPG' },
// { img: 'assets/images/12.JPG' },
// { img: 'assets/images/13.JPG' },
// { img: 'assets/images/14.JPG' },
// { img: 'assets/images/15.JPG' },
// { img: 'assets/images/17.JPG' },
// { img: 'assets/images/18.JPG' },
// { img: 'assets/images/19.JPG' },
// { img: 'assets/images/20.JPG' },
// { img: 'assets/images/21.JPG' },
// { img: 'assets/images/22.JPG' },
// { img: 'assets/images/23.JPG' },
// { img: 'assets/images/24.JPG' },
// { img: 'assets/images/25.JPG' },
// { img: 'assets/images/26.JPG' },
// { img: 'assets/images/27.JPG' },
// { img: 'assets/images/28.JPG' },
// { img: 'assets/images/29.JPG' },
// { img: 'assets/images/30.JPG' },
// { img: 'assets/images/31.JPG' },
// { img: 'assets/images/32.JPG' },
// { img: 'assets/images/33.JPG' },
// { img: 'assets/images/34.JPG' },
// { img: 'assets/images/35.JPG' },
// { img: 'assets/images/36.JPG' },
// { img: 'assets/images/37.JPG' },
// { img: 'assets/images/38.JPG' },
// { img: 'assets/images/39.JPG' },
// { img: 'assets/images/01.PNG' },
// { img: 'assets/images/02.PNG' },
// { img: 'assets/images/03.PNG' },
// { img: 'assets/images/04.PNG' },
// { img: 'assets/images/05.PNG' },
// { img: 'assets/images/06.PNG' },
// { img: 'assets/images/07.PNG' },
// { img: 'assets/images/08.PNG' },
// { img: 'assets/images/09.PNG' },
// { img: 'assets/images/10.PNG' },
// { img: 'assets/images/11.PNG' },
// { img: 'assets/images/12.PNG' },
// { img: 'assets/images/13.PNG' },
// { img: 'assets/images/14.PNG' },
// { img: 'assets/images/15.PNG' },
// { img: 'assets/images/16.PNG' },
// { img: 'assets/images/17.PNG' },
// { img: 'assets/images/18.PNG' },
// { img: 'assets/images/19.PNG' },
// { img: 'assets/images/20.PNG' },
// { img: 'assets/images/21.PNG' },
// { img: 'assets/images/22.PNG' },
// { img: 'assets/images/23.PNG' },
// { img: 'assets/images/24.PNG' },
// { img: 'assets/images/25.PNG' },
// { img: 'assets/images/26.PNG' },
// { img: 'assets/images/27.PNG' },
// { img: 'assets/images/28.PNG' },
// { img: 'assets/images/29.PNG' },
// { img: 'assets/images/30.PNG' },
// { img: 'assets/images/31.PNG' },
// { img: 'assets/images/32.PNG' },
// { img: 'assets/images/33.PNG' },
// { img: 'assets/images/34.PNG' },
// { img: 'assets/images/35.PNG' },
// { img: 'assets/images/36.PNG' },
// { img: 'assets/images/37.PNG' },
// { img: 'assets/images/38.PNG' },
// { img: 'assets/images/39.PNG' },
// { img: 'assets/images/40.PNG' },
// { img: 'assets/images/41.PNG' },
// { img: 'assets/images/42.PNG' },
// { img: 'assets/images/43.PNG' },
// { img: 'assets/images/44.PNG' },
// { img: 'assets/images/45.PNG' },
// { img: 'assets/images/46.PNG' },
// { img: 'assets/images/47.PNG' },
// { img: 'assets/images/48.PNG' },
// { img: 'assets/images/49.PNG' },
// { img: 'assets/images/50.PNG' },
// { img: 'assets/images/51.PNG' },
// { img: 'assets/images/52.PNG' },
// { img: 'assets/images/53.PNG' },
// { img: 'assets/images/54.PNG' },
// { img: 'assets/images/55.PNG' },
// { img: 'assets/images/56.PNG' },
// { img: 'assets/images/57.PNG' },
// { img: 'assets/images/58.PNG' },
// { img: 'assets/images/59.PNG' },
// { img: 'assets/images/60.PNG' },
// { img: 'assets/images/61.PNG' },
// { img: 'assets/images/62.PNG' },
// { img: 'assets/images/63.PNG' },
// { img: 'assets/images/64.PNG' },
// { img: 'assets/images/65.PNG' },
// { img: 'assets/images/66.PNG' },
// { img: 'assets/images/67.PNG' },
// { img: 'assets/images/68.PNG' },
// { img: 'assets/images/69.PNG' },
// { img: 'assets/images/70.PNG' },
// { img: 'assets/images/71.PNG' },
// { img: 'assets/images/72.PNG' },
// { img: 'assets/images/73.PNG' },
// { img: 'assets/images/74.PNG' },
// { img: 'assets/images/75.PNG' },
// { img: 'assets/images/76.PNG' },
// { img: 'assets/images/77.PNG' },
// { img: 'assets/images/78.PNG' },
// { img: 'assets/images/79.PNG' },
// { img: 'assets/images/80.PNG' },
// { img: 'assets/images/81.PNG' },
// { img: 'assets/images/82.PNG' },
// { img: 'assets/images/83.PNG' },
// { img: 'assets/images/84.PNG' },
// { img: 'assets/images/85.PNG' },
// { img: 'assets/images/86.PNG' },
// { img: 'assets/images/87.PNG' },
// { img: 'assets/images/88.PNG' },
// { img: 'assets/images/89.PNG' },
// { img: 'assets/images/90.PNG' },
// { img: 'assets/images/91.PNG' },
// { img: 'assets/images/92.PNG' },
// { img: 'assets/images/93.PNG' },
// { img: 'assets/images/94.PNG' }
