import { Slide } from '../_models/slide.model';

export const Slides: Slide[] = [
  { img: 'assets/images/189.PNG' },
  { img: 'assets/images/11.PNG' },
  { img: 'assets/images/14.PNG' },
  { img: 'assets/images/124.JPG' },
  { img: 'assets/images/128.PNG' },
  { img: 'assets/images/129.PNG' },
  { img: 'assets/images/133.JPG' },
  { img: 'assets/images/133.PNG' },
  { img: 'assets/images/137.PNG' },
  { img: 'assets/images/139.PNG' },
  { img: 'assets/images/140.PNG' },
  { img: 'assets/images/141.PNG' },
  { img: 'assets/images/142.PNG' },
  { img: 'assets/images/143.PNG' },
  { img: 'assets/images/144.PNG' },
  { img: 'assets/images/146.JPG' },
  { img: 'assets/images/146.PNG' },
  { img: 'assets/images/150.PNG' },
  { img: 'assets/images/151.PNG' },
  { img: 'assets/images/154.PNG' },
  { img: 'assets/images/155.PNG' },
  { img: 'assets/images/178.PNG' },
  { img: 'assets/images/182.PNG' },
];
