import { FAQ } from './faq.model';

export const Faqs: FAQ[] = [
    { info: 'Our mission is to provide our members the best information possible for our members to use!' },
{ info: 'We want you to make the best decisions possible for your team\'s success.' },
{ info: 'Initially we will also provide excellent data for our members to use in fantasy lineups for the NBA, Tennis and Golf.' },
{ info: 'We are striving to be "the go to site" for those that love daily and seasonal fantasy sports!' },
{ info: 'Our goal is to provide the BEST available information and insight for our members and to make it easy for our members to WIN and confidently make their line-up choices.' },
{ info: 'Our team has invested years and 1000\'s of hours to create the best information available in fantasy sports!' },
{ info: 'We love sports like you do and we love to win like you do!' },
{ info: 'I’m sure you agree, Daily Fantasy Sports (DFS) enhances the enjoyment of watching and keeping track of the games in each sport throughout the season.' },
{ info: 'At RF$, when you win, we win! Helping you win is our business!' },
{ info: 'We make winning easy by providing you with time saving analysis tools for choosing your lineups.' },
{ info: 'Our sports analysts and data scientists are not only consistent DFS players, but are also early adopters of the games.' },
{ info: 'The team at RF$ has many ties to professional sports, and we have developed a true passion for the sports and the players that we follow.' },
{ info: 'We know the immediate and critical value that real-time innovation and adaptation offers, and as such all of our tools are designed and developed in-house.' },
{ info: 'When you are picking your next set of DFS lineups, have RF$ in your corner.' },
{ info: 'The data is concise, relevant, and delivered with an edge, so you can make your decisions quickly and confidently.' },
{ info: 'Our subscribers are best described as DFS players who enjoy their sports, who are motivated and ready to win more, but always seem to run short on time due to work, family, and life in general.' },
{ info: 'The RF$ app is your one-stop DFS resource for building your winning lineups; and will always be fully functional and accessible from just about any smart device (including Android, iPhone, Tablets, computers, TVs, actually anything with a browser)' },
{ info: 'Join RF$ today and let us show you how we make it easy to win by using our stats, strategies, insights, data-viz and an ever-growing list of other time-saving, money-making player ready tools.' },
{ info: 'With the RF$ tools, expect to win More & More Often, while spending less time doing so.' },
{ info: 'The Tennis, Golf & Football reports provided by the data analysts at  Rank Fantasy $ports (RF$) are rapidly becoming some of the most sought after Daily Fantasy Sports (DFS) supplemental resources to hit the market.Why is that?' },
{ info: 'For one, their reports provide concise, easily usable time saving information.' },
{ info: 'Also, RF$ delivers their data services to subscribers using the latest cutting edge software' },
{ info: 'I’m sure you agree, Daily Fantasy Sports (DFS) enhances the enjoyment of watching and keeping track of the games in each sport all season long' },
{ info: 'At RF$, we win when you win, and we make winning easy by providing you with time saving analysis tools for choosing your lineups.' },
{ info: 'The Tennis, Golf & Football reports provided by the data analysts at  Rank Fantasy $ports (RF$) are rapidly becoming some of the most sought after Daily Fantasy Sports (DFS) supplemental resources to hit the market. Why is that?' },
{ info: 'For one, their reports provide concise, easily usable time saving information.' },
{ info: 'our sports analysts and data scientists have continued to be consistent DFS players' },
{ info: 'They were early adopters in the rapidly evolving world of DFS sports' },
{ info: 'The team has many ties to professional sports, they were strong players in the leagues they participated in' },
{ info: 'Through the years they have developed a true passion for the sports they follow and the players.' },
{ info: 'It is because of the lifestyle that they have been able to create and the joy this lifestyle brings that they feel compelled to give back, and to show and teach others how to also make playing DFS rewardingly enjoyable by consistently winning more and more often without requiring all of your free time.' },
{ info: 'Winning over $8000 on single entry $10 lineups will also be possible for you when you use the RF$ data-tables as part of your DFS playing strategy' },
{ info: 'Our data-analysts are focused daily on tracking the play-by-play, player, team, league, weather, domestic and injury reports in the sports they follow. They also maintain their own unique sets of data points in each sport.' },
{ info: 'Also, RF$ delivers their data services to subscribers using the latest cutting edge software' },
{ info: 'This progressive web app (PWA) is continuously developed with a mobile first mindset' },
{ info: 'providing subscribers with the fastest loading pages possible,' },
{ info: 'a full featured user-friendly experience on any device including iPhone & Android smart phones, tablets, TVs and any device with a browser.' },
{ info: 'Using the latest progressive web app (PWA) technology and the Google Cloud Platform delivers exceptional data, tools and resources enabling you to win more and more often' },
{ info: 'We want and even expect feedback from our subscribers, so that together we can evolve this platform to develop the best algorithm and Artificial Intelligence data models on the market.' },
{ info: 'We know the immediate and critical value that real-time innovation and adaptation offers, and as such all of our tools are designed and developed in-house.' },
{ info: 'The team is continuously evolving toolsets, by developing machine learning, deep learning, & artificial intelligence probability models and traditional statistical algorithms.' },
{ info: 'When you are picking your next set of DFS lineups, have RF$ in your corner.' },
{ info: 'The data is concise, relevant, and delivered with an edge, so you can make your decisions quickly and confidently.' },
{ info: 'Our subscribers are best described as DFS players who enjoy their sports, who are motivated and ready to be more successful more often; but, who seem to always run short on time due to work, family, and life in general.' },
{ info: 'The RF$ app is your one-stop DFS resource for building your winning lineups; and will always be fully functional and accessible from just about any smart device (including Android, iPhone, Tablets, computers, TVs, actually anything with a browser)' },
{ info: 'Join RF$ today and let us show you how we make it easy to win with our stats, strategies, insights, data-viz and other effective time-saving, money-making player ready tools.' },
{ info: 'Properly using the RF$ tools, you can expect to win more and//or more often, while spending less time doing so.' },
{ info: 'We want and even expect feedback from our subscribers, so that together we can evolve this platform to develop the best algorithm and Artificial Intelligence data models on the market.' },
]
